config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'lives#index'

  devise_for :users

  resources :lives, except: %i[show]
  resources :votes, only: %i[create destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/live.rb
# frozen_string_literal: true

class Live < ApplicationRecord
  validates :subject, presence: true

  belongs_to :author, class_name: 'User'

  has_many :votes, dependent: :destroy

  scope :suggested, -> { where(episode: nil) }
  scope :recorded, -> { where.not(episode: nil) }

  def can_be_deleted?
    votes_count.zero?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :confirmable

  validates :name, presence: true

  has_many :votes, dependent: :destroy
  has_many :voted_lives, through: :votes, source: :live
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :live, counter_cache: true
  belongs_to :user

  validates :live, uniqueness: {
    scope: :user,
    message: 'só pode votar uma vez em cada assunto'
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def layout_by_resource
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/lives_controller.rb
# frozen_string_literal: true

class LivesController < ApplicationController
  before_action :set_live, only: %i[edit update destroy]
  before_action :check_live_ownership, only: %i[edit destroy]

  def index
    lives = Live.order(votes_count: :desc, created_at: :desc)

    @suggested_lives = lives.suggested
    @recoreded_lives = lives.recorded.reorder(:episode).decorate

    @voted_lives = current_user.voted_lives
  end

  def new
    @live = Live.new
  end

  def edit; end

  def create
    @live = Live.new(live_params.merge(author: current_user))

    if @live.save
      redirect_to lives_path, notice: 'Sugestão de Live foi criada com sucesso.'
    else
      flash.now[:alert] = @live.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @live.update(live_params)
      redirect_to lives_path, notice: 'Sugestão de Live foi atualizada com sucesso.'
    else
      flash.now[:alert] = @live.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    unless @live.can_be_deleted?
      redirect_to lives_path, alert: 'Você só pode remover sugestões com zero votos'
      return
    end

    if @live.destroy
      redirect_to lives_path, notice: 'Sugestão de Live foi removida com sucesso.'
    else
      flash.now[:alert] = @live.errors.full_messages.to_sentence
      render :index
    end
  end

  private

  def set_live
    @live = Live.find(params[:id])
  end

  def live_params
    params.require(:live).permit(:subject, :description)
  end

  def check_live_ownership
    return true if @live.author == current_user

    redirect_to lives_path, alert: 'Você não tem permissão para editar/remover essa live'
  end
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  before_action :set_live, only: %i[create]

  def create
    Vote.create! live: @live, user: current_user

    redirect_to lives_path, notice: 'Seu voto foi contabilizado!'
  end

  def destroy
    vote = Vote.find(params[:id])
    vote.destroy!

    redirect_to lives_path, notice: 'Seu voto foi cancelado!'
  end

  private

  def set_live
    @live = Live.find(params[:live_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class='notification <%= type == 'notice' ? 'is-success' : 'is-danger' %>'>
    <button class='delete is-medium'></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang='pt'>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Easy Lives</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
    </head>

    <body>
      <section class="hero is-primary is-medium">
        <div class="hero-head">
          <nav class="navbar">
            <div class="container">
              <div class="navbar-brand">
                <%= link_to 'Easy Lives', root_path, class: 'navbar-item' %>

                <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                  <span></span>
                  <span></span>
                  <span></span>
                </span>
              </div>

              <% if user_signed_in? %>
                <div id="navbarMenuHeroA" class="navbar-menu">
                  <div class="navbar-end">
                    <div class="navbar-item">
                      <p>Logado como <strong><%= current_user.name %></strong></p>
                    </div>

                    <%= link_to 'Sair', destroy_user_session_path,
                      method: :delete, class: 'navbar-item' %>
                  </div>
                </div>
              <% end %>
            </div>
          </nav>
        </div>
      </section>

      <section class="section">
        <div class="container">
          <%= render 'layouts/flash_messages' %>

          <%= yield %>
        </div>
      </section>

      <footer class='footer'>
        <div class='content has-text-centered'>
          <p class='subtitle is-6'>
            Esse projeto está sendo desenvolvido ao-vivo através das
            <a href='https://www.lucascaton.com.br/lives/' target='_blank'>LIVES do Lucas Caton</a>.
          </p>

          <p class='subtitle is-6'>
            O repositório está no GitHub e é <em>open source</em>:
            <a href='https://github.com/lucascaton/easy-lives' target='_blank'>github.com/lucascaton/easy-lives</a>.
          </p>
        </div>
      </footer>
    </body>
  </html>

app/views/layouts/devise.html.erb
  <!DOCTYPE html>
  <html lang='pt'>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Easy Lives</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'authentication', media: 'all' %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    </head>

    <body>
      <section class="hero is-success is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                    <h3 class="title has-text-grey">Easy Lives</h3>
                    <p class="subtitle has-text-grey">Coloque suas credenciais para entrar.</p>

                    <div class="box">
                      <figure class="avatar">
                          <%= image_tag 'logo.png' %>
                      </figure>
                      <%= yield %>
                    </div>

                    <p class="has-text-grey">
                      <%= render "/devise/shared/links" %>
                    </p>
                </div>
            </div>
        </div>
    </section>
    </body>
  </html>

app/views/lives/_form.html.erb
<div class="columns">
  <div class="column is-half">
    <%= form_with model: live, local: true do |form| %>
      <div class="field">
        <%= form.label :subject, class: 'label' %>
        <div class="control">
          <%= form.text_field :subject, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <%= form.label :description, class: 'label' %>
        <div class="control">
          <%= form.text_area :description, class: 'textarea' %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit 'Salvar', class: 'button is-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lives/_list.html.erb
<h3 class='is-size-3'><%= title %> </h3>

<table id='lives' class='table is-striped'>
  <thead>
    <tr>
      <% if local_assigns.fetch(:voted_lives, nil) %>
        <th class='votes'><%= t '.vote' %></th>
      <% else %>
        <th class='episode'><%= t '.episode' %></th>
      <% end %>

      <th><%= t 'activerecord.attributes.live.subject' %></th>
      <th><%= t 'activerecord.attributes.live.description' %></th>
      <th class='author'><%= t 'activerecord.attributes.live.author' %></th>
      <th class='created_at'><%= t 'activerecord.attributes.live.created_at' %></th>

      <% if local_assigns.fetch(:voted_lives, nil) %>
        <th class='actions'></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% lives.each do |live| %>
      <tr>
        <td>
          <% if local_assigns.fetch(:voted_lives, nil) %>
            <span class='tag is-info'><%= live.votes_count %></span>

            <% if voted_lives.include?(live) %>
              <%= link_to vote_path(live.votes.where(user: current_user).first),
                method: :delete, class: 'tooltip',
                  data: { tooltip: 'Remover voto' } do %>
                  <span class='tag is-success'>✔</span>
              <% end %>
            <% else %>
              <%= link_to votes_path(live_id: live.id),
                method: :post, class: 'tooltip',
                data: { tooltip: 'Votar' } do %>
                  <span class='tag'>✔</span>
              <% end %>
            <% end %>
          <% else %>
            <%= live.formatted_episode %>
          <% end %>
        </td>

        <td><%= live.subject %></td>
        <td><%= live.description %></td>

        <td class='author-column'>
          <%= image_tag live.author.decorate.avatar_url, class: 'avatar' %>
          <span><%= live.author.name %></span>
        </td>

        <td><%= l live.created_at, format: :short %></td>

        <% if local_assigns.fetch(:voted_lives, nil) %>
          <td>
            <% if live.author == current_user %>
              <%= link_to 'Editar', edit_live_path(live), class: 'button is-success is-small' %>
            <% end %>

            <% if live.author == current_user && live.can_be_deleted? %>
              <%= link_to 'Remover', live_path(live), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'button is-danger is-small' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lives/edit.html.erb
<h3 class='is-size-3'>Editar Live</h3>

<%= render 'form', live: @live %>

app/views/lives/index.html.erb
<%= link_to 'Sugerir live', new_live_path, class: 'button is-primary is-pulled-right' %>

<%= render 'list', lives: @suggested_lives, title: 'Sugestões de Lives', voted_lives: @voted_lives %>
<%= render 'list', lives: @recoreded_lives, title: 'Lives Gravadas' %>

app/views/lives/new.html.erb
<h3 class='is-size-3'>Sugerir Live</h3>

<%= render 'form', live: @live %>